# Generated by Django 5.1.1 on 2024-09-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accomodation_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='trasport_id',
        ),
        migrations.DeleteModel(
            name='Accomodation',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
